# Site settings
title: AppSense.me - 创意惊艳世界!
email: admin@appsense.me
description: > # this means to ignore newlines until "baseurl:"
  appsense studio致力于开发「简单／高效／惊艳／开源」的移动应用，您可以提交自己的创意，我们来实现您的想法。
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.appsense.me" # the base hostname & protocol for your site
url: "http://192.168.1.106:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "page:num"
timezone: Asia/Shanghai
